# Generated by Django 5.2.7 on 2025-10-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('category', models.CharField(choices=[('LP', 'Laptop'), ('PN', 'Phone'), ('CNS', 'Console'), ('WCH', 'Watch'), ('HM', 'Home'), ('OT', 'Other'), ('DF', 'Default')], default='DF', verbose_name='Category')),
                ('buyout_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Buyout price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=10, verbose_name='Duration')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Rental price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='shop.product', verbose_name='Product')),
            ],
        ),
    ]
