# Generated by Django 5.2.7 on 2025-10-15 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_alter_priceplan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_cart_items', to='shop.priceplan', verbose_name='Rental plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='shop.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_cart', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
